---
- name: Get secrets from vault
  hosts: all
  gather_facts: false
  roles:
    - role: bmstu.vats.init
      vault_path_inventory: bots/data/deploy,inventory-secrets.yaml
      vault_path_secrets:   bots/data/baumanec,baumanec-achievments-secrets.yaml
  tasks:
    - name: Init a new swarm with default parameters
      community.docker.docker_swarm:
        state: present

    - name: Run bot docker service
      docker_swarm_service:
        name: baumanec-achievments-bot
        image: twobrowin/baumanec-achievments-bot:1.0.2
        env:
          TZ: "Europe/Moscow"
          
          BOT_TOKEN:       "{{ secrets.bot_token }}"
          SHEETS_ACC_JSON: "{{ secrets.sheet_acc_json | string }}"
          SHEETS_LINK:     "{{ secrets.sheets_link }}"

          SWITCH_UPDATE_TIME:   '15'
          SETTINGS_UPDATE_TIME: '35'